apiVersion: v1
kind: Service
metadata:
  name: netflixappservice
  labels:
    app: netflix-app
spec:
  type: NodePort
  selector:
    app: netflix-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
